### ISSUE TITLE
Load trained model

### ISSUE THREAD

**Issue by edgarriba** [hughperkins/pytorch#15]
@hughperkins  Do you support load an existing trained model?

**Comment by hughperkins** [comment]
Yes!  I mean, on the lua side anyway.  For example, you can have a look at https://github.com/hughperkins/pytorch-residual-networks/blob/pytorch/residual_trainer.lua#L58

But I guess you mean, can I load a `.t7` directly into a Pytorch tensor, from the Python side? In which case... I need to think about that :-P

**Comment by edgarriba** [comment]
Yes, second use case. I want to interact with opencv python and a t7 file

**Comment by hughperkins** [comment]
Ok.  Started looking at this in 6aa2f19f4   Seems like save maybe works.  You might be able to add in load, using same approach?  Otherwise I will look at this tomorrow-ish

**Comment by edgarriba** [comment]
thx!

**Comment by hughperkins** [comment]
Implemented in 0f129c0  You should be able to do:

```
import PyTorchAug

PyTorchAug.save('/tmp/foo.t7', sometensor)
result = PyTorchAug.load('/tmp/foo.t7')
```
You can look at [test/test_save_load.py](https://github.com/hughperkins/pytorch/tree/master/test/test_save_load.py) for an example

**Comment by hughperkins** [comment]
Can you confirm this does/doesnt work?

**Comment by sunshineatnoon** [comment]
@hughperkins This works fine, thanks for this great work!

**Comment by hughperkins** [comment]
Cool.  Thank you @sunshineatnoon :-)

**Comment by dyzhou2015** [comment]
Can I load a Gpu-trained model ? I mean the parameter of the model is CudaTensor. Thanks

**Comment by wangdelp** [comment]
Still not clear how to use trained model. I can use torch.load(file_path) to get the weights, but how do I use these weights to initialize the network? Thank you.
