### ISSUE TITLE
Installation fails due to unknown '.pyx' file type

### ISSUE THREAD

**Issue by mlosch** [hughperkins/pytorch#16]
Following the installation instructions, the install fails after typing `./build.sh` with the following message:
`error: unknown file type '.pyx' (from 'src/Storage.pyx')`

I could fix it by installing `python-pyrex`, but that should be listed in the instructions.

**Comment by hughperkins** [comment]
Fair point.  Maybe addressed in 6eb4a40 (there should be no need for cython/pyrex, simply for installation purposes; but I think there might have been a bug in my `setup.py` that was inadvertently requiring them).

**Comment by hughperkins** [comment]
travis build passed https://travis-ci.org/hughperkins/pytorch/builds/161540535   I guess the change should be ok?

**Comment by mlosch** [comment]
Removed `python-pyrex` and was able to reinstall pytorch without issues. Thanks and closed :+1:

**Comment by hughperkins** [comment]
Cool :-)  Thank you for having taken the time to confirm it is ok now, Max.
