### ISSUE TITLE
Can I save numpy arrays in .t7 using pytorch ?

### ISSUE THREAD

**Issue by sunshineatnoon** [hughperkins/pytorch#17]
I have some arrays generated by a python script and I want to save them as .t7 tensors used in torch, is this possible in pytorch ? Or maybe use pytorch to load pickle files ? Thanks!

**Comment by hughperkins** [comment]
Yes :-)  See https://github.com/hughperkins/pytorch/blob/master/test/test_save_load.py

**Comment by sunshineatnoon** [comment]
@hughperkins Thanks, figured it out

**Comment by hughperkins** [comment]
Cool :-)
