### ISSUE TITLE
load torch pretrained model error :Exception: /home/jcc/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <nn.gModule> stack traceback:

### ISSUE THREAD

**Issue by brisker** [hughperkins/pytorch#27]
load torch pretrained model error :Exception: /home/jcc/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <nn.gModule> stack traceback:

with 
import PyTorchAug
import PyTorch
already done

**Comment by achalddave** [comment]
This seems to be the same issue as #24 . Try adding `PyTorch.require('nngraph')`.
