### ISSUE TITLE
Can't install pytorch

### ISSUE THREAD

**Issue by rylm** [hughperkins/pytorch#30]
I've successfully built pytorch but `run_tests.sh` fails with `./run_tests.sh: line 25: py.test: command not found` and installing as library `(python3 setup.py install)` fails with `src/lua.cpp:248:10: fatal error: 'THRandom.h' file not found`

What should I do?

**Comment by rylm** [comment]
Actually now tests can run, `THRandom.h ` is still not found, even though it is located in included directory

**Comment by mingliangfu** [comment]
Hi @rylm, has the issue been solved? If so, can you post more details
