### ISSUE TITLE
Jupyter notebook dies

### ISSUE THREAD

**Issue by lpuglia** [hughperkins/pytorch#43]
If i try to do even the most basic thing into a ipython notebook:

```
import PyTorch
```

The notebook dies:

```
The kernel appears to have died. It will restart automatically.
```

But the import (and all the other functionality) works good in a normal python terminal, any idea why this is happening?

**Comment by hughperkins** [comment]
No clue. I guess it might be something related to `sys.path` perhaps? I dont have time to look unfortunately. If it was me, I think I'd try importing lower level things, and work my way up. Maybe sprinkle the import sections of the code liberally with `print` statements, so I can see where it dies.

**Comment by hughperkins** [comment]
(like, I guess something like, at some point the underlying compiled .so gets imported, fails somehow, dies)

**Comment by lpuglia** [comment]
Ok, i checked the jupyter log and I got:

```
PANIC: unprotected error in call to Lua API (module 'torch' not found:
        no field package.preload['torch']
        no file '/home/lpuglia/.luarocks/share/lua/5.1/torch.lua'
        no file '/home/lpuglia/.luarocks/share/lua/5.1/torch/init.lua'
        no file '/opt/torch/install/share/lua/5.1/torch.lua'
        no file '/opt/torch/install/share/lua/5.1/torch/init.lua'
        no file './torch.lua'
        no file '/opt/torch/install/share/luajit-2.1.0-beta1/torch.lua'
        no file '/usr/local/share/lua/5.1/torch.lua'
        no file '/usr/local/share/lua/5.1/torch/init.lua'
        no file '/opt/torch/install/lib/torch.so'
        no file '/home/lpuglia/.luarocks/lib/lua/5.1/torch.so'
        no file '/opt/torch/install/lib/lua/5.1/torch.so'
        no file './torch.so'
        no file '/usr/local/lib/lua/5.1/torch.so'
        no file '/usr/local/lib/lua/5.1/loadall.so')
```

This is weird since it works good on the normal terminal

**Comment by hughperkins** [comment]
Ok. Looks like a path issue. Might be the torch path.

**Comment by lpuglia** [comment]
`Have you tried to turn it off and on again?`
I should have tried this before opening an issue :D

**Comment by hughperkins** [comment]
:)
